Movie Recommendation System

Phase 1: Data Understanding

- Loading datasets
- Understanding dataset structure
- Exploring columns
- Checking data types
- Finding missing values
- Identifying duplicate records
- Initial exploratory analysis

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# Display all columns
pd.set_option("display.max_columns", None)
# Display wider tables
pd.set_option("display.width", 1000)

In [3]:
movies = pd.read_csv("../data/raw/tmdb_5000_movies.csv")
credits = pd.read_csv("../data/raw/tmdb_5000_credits.csv")

In [5]:
movies.head(3)

      budget                                             genres                                      homepage      id                                           keywords original_language                            original_title                                           overview  popularity                               production_companies                               production_countries release_date     revenue  runtime                                   spoken_languages    status                                         tagline                                     title  vote_average  vote_count
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...                   http://www.avatarmovie.com/   19995  [{"id": 1463, "name": "culture clash"}, {"id":...                en                                    Avatar  In the 22nd century, a paraplegic Marine is di...  150.437577  [{"name": "Ingenious Film Partners", "id": 289...  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released                     Enter the World of Pandora.                                    Avatar           7.2       11800
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...  http://disney.go.com/disneypictures/pirates/     285  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en  Pirates of the Caribbean: At World's End  Captain Barbossa, long believed to be dead, ha...  139.082615  [{"name": "Walt Disney Pictures", "id": 2}, {"...  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000    169.0           [{"iso_639_1": "en", "name": "English"}]  Released  At the end of the world, the adventure begins.  Pirates of the Caribbean: At World's End           6.9        4500
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   http://www.sonypictures.com/movies/spectre/  206647  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en                                   Spectre  A cryptic message from Bond’s past sends him o...  107.376788  [{"name": "Columbia Pictures", "id": 5}, {"nam...  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released                           A Plan No One Escapes                                   Spectre           6.3        4466

In [6]:
credits.head()

   movie_id                                     title                                               cast                                               crew
0     19995                                    Avatar  [{"cast_id": 242, "character": "Jake Sully", "...  [{"credit_id": "52fe48009251416c750aca23", "de...
1       285  Pirates of the Caribbean: At World's End  [{"cast_id": 4, "character": "Captain Jack Spa...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2    206647                                   Spectre  [{"cast_id": 1, "character": "James Bond", "cr...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3     49026                     The Dark Knight Rises  [{"cast_id": 2, "character": "Bruce Wayne / Ba...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     49529                               John Carter  [{"cast_id": 5, "character": "John Carter", "c...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

In [7]:
print("Movies Dataset Shape:", movies.shape)
print("Credits Dataset Shape:", credits.shape)

Movies Dataset Shape: (4803, 20)
Credits Dataset Shape: (4803, 4)

In [10]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   str
 2   homepage              1712 non-null   str
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   str
 5   original_language     4803 non-null   str
 6   original_title        4803 non-null   str
 7   overview              4800 non-null   str
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   str
 10  production_countries  4803 non-null   str
 11  release_date          4802 non-null   str
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   str
 15  status                4803 non-null   str
 16  tagline               3959 non-null   str
 17  title                 4803 non-null   str
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), str(13)
memory usage: 5.4 MB

In [11]:
credits.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   str
 2   cast      4803 non-null   str
 3   crew      4803 non-null   str
dtypes: int64(1), str(3)
memory usage: 33.8 MB

In [12]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language', 'original_title', 'overview', 'popularity', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title', 'vote_average', 'vote_count'], dtype='str')

Important columns: Genres, Title, Language, Vote Average, Overview

In [13]:
credits.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='str')

Important columns: Cast, Crew

In [14]:
movies.describe()

             budget             id   popularity       revenue      runtime  vote_average    vote_count
count  4.803000e+03    4803.000000  4803.000000  4.803000e+03  4801.000000   4803.000000   4803.000000
mean   2.904504e+07   57165.484281    21.492301  8.226064e+07   106.875859      6.092172    690.217989
std    4.072239e+07   88694.614033    31.816650  1.628571e+08    22.611935      1.194612   1234.585891
min    0.000000e+00       5.000000     0.000000  0.000000e+00     0.000000      0.000000      0.000000
25%    7.900000e+05    9014.500000     4.668070  0.000000e+00    94.000000      5.600000     54.000000
50%    1.500000e+07   14629.000000    12.921594  1.917000e+07   103.000000      6.200000    235.000000
75%    4.000000e+07   58610.500000    28.313505  9.291719e+07   118.000000      6.800000    737.000000
max    3.800000e+08  459488.000000   875.581305  2.787965e+09   338.000000     10.000000  13752.000000

Highest budget:3.800000e+08
Highest revenue:2.787965e+09
Average rating:6.09
Maximum runtime:338 mins

In [16]:
#Missing values
movies.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [17]:
credits.isnull().sum()

movie_id    0
title       0
cast        0
crew        0
dtype: int64

In [18]:
#Duplicates
print("Movies duplicates:", movies.duplicated().sum())
print("Credits duplicates:", credits.duplicated().sum())

Movies duplicates: 0
Credits duplicates: 0

# SUMMARY